version: '3'

services:
  deploy:
    build:
      context: .
    restart: always
    ports:
      - '127.0.0.1:${API_PORT}:8000'
    networks:
      - blogdb
    environment:
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}

networks:
  blogdb:
    external: true
